//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiyatMandli.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PiyatMandliEntities : DbContext
    {
        public PiyatMandliEntities()
            : base("name=PiyatMandliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<FarmerLand> FarmerLands { get; set; }
        public virtual DbSet<Farmer> Farmers { get; set; }
        public virtual DbSet<WindowMaster> WindowMasters { get; set; }
        public virtual DbSet<YearMaster> YearMasters { get; set; }
    }
}
