//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiyatMandli.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int FarmerId { get; set; }
        public int LandId { get; set; }
        public Nullable<int> GarotdarId { get; set; }
        public string Date { get; set; }
        public string LandArea { get; set; }
        public string Rate { get; set; }
        public string Crop { get; set; }
        public int YearId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsDeleted { get; set; }
        public decimal RateEng { get; set; }
        public decimal LandAreaEng { get; set; }
        public System.DateTime DateEng { get; set; }
    
        public virtual FarmerLand FarmerLand { get; set; }
        public virtual Farmer Farmer { get; set; }
        public virtual Farmer Garotdar { get; set; }
        public virtual YearMaster YearMaster { get; set; }
    }
}
